/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['LoginRequest'];
        };
      };
      responses: {
        /** @description Login successful */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['LoginResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get current user */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Current user */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['UserResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/brands': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all brands */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of brands */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              data: components['schemas']['BrandResponse'][];
              pagination: {
                limit: number;
                page: number;
                total: number;
                totalPages: number;
              };
            };
          };
        };
      };
    };
    put?: never;
    /** Create brand */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['CreateBrandRequest'];
        };
      };
      responses: {
        /** @description Brand created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['BrandResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/brands/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update brand */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            /** @example Musical instruments manufacturer */
            description?: string | null;
            /** @example Yamaha */
            name?: string;
          };
        };
      };
      responses: {
        /** @description Brand updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['BrandResponse'];
          };
        };
      };
    };
    post?: never;
    /** Delete brand */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Brand deleted */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              message: string;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/departments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all departments */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of departments */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              data: components['schemas']['DepartmentResponse'][];
              pagination: {
                limit: number;
                page: number;
                total: number;
                totalPages: number;
              };
            };
          };
        };
      };
    };
    put?: never;
    /** Create department */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['CreateDepartmentRequest'];
        };
      };
      responses: {
        /** @description Department created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['DepartmentResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/departments/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update department */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            /** @example Audio equipment */
            description?: string | null;
            /** @example Audio */
            name?: string;
          };
        };
      };
      responses: {
        /** @description Department updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['DepartmentResponse'];
          };
        };
      };
    };
    post?: never;
    /** Delete department */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Department deleted */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              message: string;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/equipment': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all equipment */
    get: {
      parameters: {
        query?: {
          brandId?: string;
          departmentId?: string;
          limit?: string;
          page?: string;
          search?: string;
          status?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Paginated list of equipment */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              data: components['schemas']['EquipmentResponse'][];
              pagination: {
                limit: number;
                page: number;
                total: number;
                totalPages: number;
              };
            };
          };
        };
      };
    };
    put?: never;
    /** Create equipment */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['CreateEquipmentRequest'];
        };
      };
      responses: {
        /** @description Equipment created */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/equipment/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get equipment by ID */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Equipment details */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['EquipmentResponse'];
          };
        };
      };
    };
    /** Update equipment */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            brandId?: string | null;
            departmentId?: string | null;
            name?: string;
            /** Format: date-time */
            purchaseDate?: string | null;
            /**
                         * @default new
                         * @enum {string}
                         */
            status?: 'new' | 'old' | 'damaged' | 'repairing' | 'disposed';
          };
        };
      };
      responses: {
        /** @description Equipment updated */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    /** Delete equipment */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Equipment deleted */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/equipment/{id}/qrcode': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get equipment QR code */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description QR Code */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              qrCode: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    BrandResponse: {
      /**
             * Format: date-time
             * @example 2024-01-01T00:00:00.000Z
             */
      createdAt: string;
      creator?: components['schemas']['UserResponse'] & unknown;
      /** @example Musical instruments manufacturer */
      description?: string | null;
      /** @example cm1... */
      id: string;
      /** @example Yamaha */
      name: string;
    };
    CreateBrandRequest: {
      /** @example Musical instruments manufacturer */
      description?: string | null;
      /** @example Yamaha */
      name: string;
    };
    CreateDepartmentRequest: {
      /** @example Audio equipment */
      description?: string | null;
      /** @example Audio */
      name: string;
    };
    CreateEquipmentRequest: {
      brandId?: string | null;
      departmentId?: string | null;
      name: string;
      /** Format: date-time */
      purchaseDate?: string | null;
      /**
             * @default new
             * @enum {string}
             */
      status: 'new' | 'old' | 'damaged' | 'repairing' | 'disposed';
    };
    DepartmentResponse: {
      /**
             * Format: date-time
             * @example 2024-01-01T00:00:00.000Z
             */
      createdAt: string;
      creator?: components['schemas']['UserResponse'] & unknown;
      /** @example Audio equipment */
      description?: string | null;
      /** @example cm1... */
      id: string;
      /** @example Audio */
      name: string;
    };
    EquipmentResponse: {
      brand?: components['schemas']['BrandResponse'] & unknown;
      brandId?: string | null;
      createdBy?: string | null;
      creator?: components['schemas']['UserResponse'] & unknown;
      department?: components['schemas']['DepartmentResponse'] & unknown;
      departmentId?: string | null;
      /** @example cm1... */
      id: string;
      /** @example Microphone SM58 */
      name: string;
      /**
             * Format: date-time
             * @example 2024-01-01T00:00:00.000Z
             */
      purchaseDate: string | null;
      /**
             * @example new
             * @enum {string}
             */
      status: 'new' | 'old' | 'damaged' | 'repairing' | 'disposed';
    };
    LoginRequest: {
      password: string;
      username: string;
    };
    LoginResponse: {
      token: string;
      user: components['schemas']['UserResponse'];
    };
    UserResponse: {
      /** @example cm1... */
      id: string;
      /** @example John Doe */
      name: string;
      /**
             * @example user
             * @enum {string}
             */
      role: 'user' | 'admin';
      /** @example johndoe */
      username: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type BrandResponse = components['schemas']['BrandResponse']
export type CreateBrandRequest = components['schemas']['CreateBrandRequest']
export type CreateDepartmentRequest = components['schemas']['CreateDepartmentRequest']
export type CreateEquipmentRequest = components['schemas']['CreateEquipmentRequest']
export type DepartmentResponse = components['schemas']['DepartmentResponse']
export type EquipmentResponse = components['schemas']['EquipmentResponse']
export type LoginRequest = components['schemas']['LoginRequest']
export type LoginResponse = components['schemas']['LoginResponse']
export type UserResponse = components['schemas']['UserResponse']
export type $defs = Record<string, never>
export type operations = Record<string, never>
